#!/usr/bin/env python3
"""
extract-content.py - ドキュメントファイルの本文を読み込み、
dashboard.html の seedData() に埋め込むための JavaScript コードを生成する。

使用方法:
  cd docs/02progressmanagement
  python3 tools/extract-content.py > tools/content-data.js
"""

import os
import json

# ドキュメントIDとファイルパスのマッピング（.md と .json のみ）
# .html ファイルは別タブで開くため埋め込み不要
DOCS = [
    ("DOC-C-01", "01systemdesign/01_要件定義書.md"),
    ("DOC-C-02", "01systemdesign/02_基本設計書.md"),
    ("DOC-C-03", "01systemdesign/03_詳細設計書.md"),
    ("DOC-C-04", "01systemdesign/04_アーキテクチャ設計書.md"),
    ("DOC-C-05", "01systemdesign/05_技術スタック設計書.md"),
    ("DOC-C-06", "01systemdesign/06_実装計画書.md"),
    ("DOC-A-01", "01systemdesign/fragrance-app-architecture.md"),
    ("DOC-A-02", "01systemdesign/fragrance-app-architecture-v2.md"),
    ("DOC-A-03", "01systemdesign/hybrid-blend-architecture.md"),
    ("DOC-A-04", "01systemdesign/theme-layer-architecture.md"),
    ("DOC-Q-01", "01systemdesign/testing-strategy.md"),
    ("DOC-Q-02", "01systemdesign/threat-model.md"),
    ("DOC-Q-03", "01systemdesign/development-stack.md"),
    ("DOC-Q-04", "01systemdesign/operations-supplement.md"),
    ("DOC-K-01", "01systemdesign/architecture-review-framework.md"),
    ("DOC-K-02", "01systemdesign/karf-review-report.md"),
    ("DOC-K-03", "01systemdesign/karf/karf-workflow.md"),
    ("DOC-K-05", "01systemdesign/karf/results/2026-02-17.json"),
    ("DOC-F-01", "01systemdesign/features/auth-user-management.md"),
    ("DOC-F-02", "01systemdesign/features/blend-system.md"),
    ("DOC-F-03", "01systemdesign/features/cart-checkout-orders.md"),
    ("DOC-F-04", "01systemdesign/features/admin-dashboard.md"),
    ("DOC-F-05", "01systemdesign/features/creator-system.md"),
    ("DOC-F-06", "01systemdesign/features/ec-shop.md"),
    ("DOC-F-07", "01systemdesign/features/review-system.md"),
    ("DOC-F-08", "01systemdesign/features/receipt-invoice.md"),
    ("DOC-F-09", "01systemdesign/features/coupon-promotion.md"),
    ("DOC-F-10", "01systemdesign/features/ec-settings.md"),
    ("DOC-F-11", "01systemdesign/features/royalty-system.md"),
    ("DOC-F-12", "01systemdesign/features/shipping-address.md"),
    ("DOC-F-13", "01systemdesign/features/notification-system.md"),
    ("DOC-F-14", "01systemdesign/features/fragrance-map.md"),
    ("DOC-F-15", "01systemdesign/features/recipe-system.md"),
    ("DOC-F-16", "01systemdesign/features/footprint-tracking.md"),
    ("DOC-F-17", "01systemdesign/features/ux-patterns.md"),
    ("DOC-F-18", "01systemdesign/features/operations-infrastructure.md"),
    ("DOC-S-01", "01systemdesign/creator-tier-system.md"),
    ("DOC-S-02", "01systemdesign/creator-award-system.md"),
    ("DOC-P-01", "context-log.md"),
]

def escape_js_string(s):
    """JavaScript文字列リテラル内で安全に使えるようにエスケープ"""
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '')
    s = s.replace('\t', '\\t')
    s = s.replace('</script>', '<\\/script>')
    return s

def main():
    base_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
    base_dir = os.path.normpath(base_dir)

    print("  // Document contents (auto-generated by extract-content.py)")
    print("  var docContents = [")

    total_size = 0
    count = 0

    for doc_id, rel_path in DOCS:
        full_path = os.path.join(base_dir, rel_path)
        if not os.path.exists(full_path):
            print(f"    // WARNING: {rel_path} not found", file=__import__('sys').stderr)
            continue

        with open(full_path, 'r', encoding='utf-8') as f:
            content = f.read()

        escaped = escape_js_string(content)
        total_size += len(content)
        count += 1

        comma = ',' if count < len(DOCS) else ''
        print(f"    ['{doc_id}','{escaped}']{comma}")

    print("  ];")
    print("  docContents.forEach(function(r){ DB.run('UPDATE documents SET content=? WHERE id=?', [r[1], r[0]]); });")

    import sys
    print(f"\n  // {count} documents, ~{total_size // 1024}KB total content", file=sys.stderr)

if __name__ == '__main__':
    main()
