import { FLAVOR_COORDINATES } from "./flavor-coordinates";
import type { ReferenceFragrance } from "./types";

/**
 * マップ座標を配合ベクトルから計算する（加重平均）
 */
function calcPosition(vector: Record<string, number>): {
  x: number;
  y: number;
} {
  let x = 0;
  let y = 0;
  let totalWeight = 0;
  for (const [flavor, weight] of Object.entries(vector)) {
    const coord = FLAVOR_COORDINATES[flavor];
    if (coord && weight > 0) {
      x += coord.x * weight;
      y += coord.y * weight;
      totalWeight += weight;
    }
  }
  if (totalWeight === 0) return { x: 0, y: 0 };
  return { x: x / totalWeight, y: y / totalWeight };
}

function frag(data: Omit<ReferenceFragrance, "position">): ReferenceFragrance {
  return { ...data, position: calcPosition(data.vector) };
}

/**
 * 25種の有名フレグランス — リファレンスデータ
 * vectorは26香料への近似配合（合計1.0）
 */
export const REFERENCE_FRAGRANCES: ReferenceFragrance[] = [
  // ─── フレッシュ・シトラス ───
  frag({
    id: "acqua-di-gio",
    name: "Acqua di Gio",
    nameJa: "アクア ディ ジオ",
    brand: "Giorgio Armani",
    category: "フレッシュ・シトラス",
    gender: "men",
    vector: {
      ライム: 0.15,
      レモン: 0.1,
      ベルガモット: 0.15,
      シーブルー: 0.25,
      ジャスミン: 0.05,
      ミュゲ: 0.05,
      シダーウッド: 0.1,
      ムスク: 0.1,
      パチュリ: 0.05,
    },
  }),
  frag({
    id: "ck-one",
    name: "CK One",
    nameJa: "シーケーワン",
    brand: "Calvin Klein",
    category: "フレッシュ・シトラス",
    gender: "unisex",
    vector: {
      ベルガモット: 0.15,
      レモン: 0.15,
      オレンジ: 0.1,
      ラベンダー: 0.1,
      ミュゲ: 0.1,
      スウィートローズ: 0.05,
      ムスク: 0.2,
      シダーウッド: 0.1,
      アンバー: 0.05,
    },
  }),
  frag({
    id: "light-blue",
    name: "Light Blue",
    nameJa: "ライトブルー",
    brand: "Dolce & Gabbana",
    category: "フレッシュ・シトラス",
    gender: "women",
    vector: {
      レモン: 0.2,
      グレープフルーツ: 0.1,
      ベルガモット: 0.1,
      ジャスミン: 0.1,
      スウィートローズ: 0.1,
      ミュゲ: 0.05,
      シダーウッド: 0.15,
      ムスク: 0.1,
      アンバー: 0.1,
    },
  }),
  frag({
    id: "eau-de-cologne-imperiale",
    name: "Eau de Cologne Imperiale",
    nameJa: "オーデコロン アンペリアル",
    brand: "Guerlain",
    category: "フレッシュ・シトラス",
    gender: "unisex",
    vector: {
      レモン: 0.2,
      ベルガモット: 0.25,
      オレンジ: 0.2,
      ラベンダー: 0.1,
      ミュゲ: 0.05,
      ムスク: 0.15,
      シダーウッド: 0.05,
    },
  }),

  // ─── フレッシュ・フローラル ───
  frag({
    id: "daisy",
    name: "Daisy",
    nameJa: "デイジー",
    brand: "Marc Jacobs",
    category: "フレッシュ・フローラル",
    gender: "women",
    vector: {
      グレープフルーツ: 0.1,
      ベルガモット: 0.1,
      ガーデニア: 0.15,
      ジャスミン: 0.15,
      ミュゲ: 0.15,
      ムスク: 0.15,
      サンダルウッド: 0.1,
      バニラ: 0.1,
    },
  }),
  frag({
    id: "chance-eau-fraiche",
    name: "Chance Eau Fraiche",
    nameJa: "チャンス オー フレッシュ",
    brand: "CHANEL",
    category: "フレッシュ・フローラル",
    gender: "women",
    vector: {
      レモン: 0.1,
      グレープフルーツ: 0.1,
      ジャスミン: 0.15,
      ミュゲ: 0.15,
      マグノリア: 0.1,
      ムスク: 0.15,
      パチュリ: 0.1,
      シダーウッド: 0.1,
      アンバー: 0.05,
    },
  }),
  frag({
    id: "miss-dior-blooming-bouquet",
    name: "Miss Dior Blooming Bouquet",
    nameJa: "ミス ディオール ブルーミング ブーケ",
    brand: "Dior",
    category: "フレッシュ・フローラル",
    gender: "women",
    vector: {
      オレンジ: 0.1,
      ベルガモット: 0.1,
      スウィートローズ: 0.2,
      ダマスククラシックローズ: 0.1,
      ミュゲ: 0.15,
      ムスク: 0.2,
      パチュリ: 0.1,
      シダーウッド: 0.05,
    },
  }),

  // ─── フローラル中心 ───
  frag({
    id: "chanel-no5",
    name: "Chanel No.5",
    nameJa: "シャネル No.5",
    brand: "CHANEL",
    category: "フローラル",
    gender: "women",
    vector: {
      ベルガモット: 0.05,
      レモン: 0.05,
      ジャスミン: 0.2,
      スウィートローズ: 0.15,
      ミュゲ: 0.1,
      ダフネ: 0.05,
      サンダルウッド: 0.15,
      バニラ: 0.1,
      アンバー: 0.1,
      ムスク: 0.05,
    },
  }),
  frag({
    id: "jadore",
    name: "J'adore",
    nameJa: "ジャドール",
    brand: "Dior",
    category: "フローラル",
    gender: "women",
    vector: {
      ベルガモット: 0.05,
      オレンジ: 0.05,
      ジャスミン: 0.2,
      スウィートローズ: 0.15,
      チュベローズ: 0.15,
      マグノリア: 0.1,
      サンダルウッド: 0.1,
      ムスク: 0.1,
      バニラ: 0.1,
    },
  }),
  frag({
    id: "flowerbomb",
    name: "Flowerbomb",
    nameJa: "フラワーボム",
    brand: "Viktor & Rolf",
    category: "フローラル",
    gender: "women",
    vector: {
      ベルガモット: 0.05,
      ジャスミン: 0.15,
      スウィートローズ: 0.15,
      ガーデニア: 0.1,
      マグノリア: 0.1,
      パチュリ: 0.15,
      ムスク: 0.1,
      バニラ: 0.15,
      アンバー: 0.05,
    },
  }),
  frag({
    id: "chloe-edp",
    name: "Chloe EDP",
    nameJa: "クロエ オードパルファム",
    brand: "Chloe",
    category: "フローラル",
    gender: "women",
    vector: {
      ベルガモット: 0.05,
      ライム: 0.05,
      スウィートローズ: 0.25,
      ダマスククラシックローズ: 0.15,
      ミュゲ: 0.1,
      マグノリア: 0.1,
      シダーウッド: 0.15,
      アンバー: 0.1,
      ムスク: 0.05,
    },
  }),

  // ─── ウォーム・フローラル ───
  frag({
    id: "black-opium",
    name: "Black Opium",
    nameJa: "ブラック オピウム",
    brand: "Yves Saint Laurent",
    category: "ウォーム・フローラル",
    gender: "women",
    vector: {
      オレンジ: 0.05,
      ベルガモット: 0.05,
      ジャスミン: 0.15,
      ガーデニア: 0.1,
      バニラ: 0.25,
      アンバー: 0.15,
      パチュリ: 0.1,
      サンダルウッド: 0.1,
      ムスク: 0.05,
    },
  }),
  frag({
    id: "la-vie-est-belle",
    name: "La Vie Est Belle",
    nameJa: "ラ ヴィ エ ベル",
    brand: "Lancome",
    category: "ウォーム・フローラル",
    gender: "women",
    vector: {
      カシス: 0.05,
      オレンジ: 0.05,
      ジャスミン: 0.1,
      ガーデニア: 0.1,
      スウィートローズ: 0.1,
      バニラ: 0.2,
      パチュリ: 0.15,
      アンバー: 0.15,
      ムスク: 0.1,
    },
  }),
  frag({
    id: "mon-paris",
    name: "Mon Paris",
    nameJa: "モン パリ",
    brand: "Yves Saint Laurent",
    category: "ウォーム・フローラル",
    gender: "women",
    vector: {
      カシス: 0.1,
      ベルガモット: 0.05,
      ダフネ: 0.1,
      ジャスミン: 0.1,
      ガーデニア: 0.1,
      パチュリ: 0.15,
      アンバー: 0.15,
      バニラ: 0.15,
      ムスク: 0.1,
    },
  }),

  // ─── ウッディ・フレッシュ ───
  frag({
    id: "terre-dhermes",
    name: "Terre d'Hermes",
    nameJa: "テール ドゥ エルメス",
    brand: "Hermes",
    category: "ウッディ・フレッシュ",
    gender: "men",
    vector: {
      グレープフルーツ: 0.15,
      オレンジ: 0.1,
      カーネーション: 0.05,
      ブラックペッパー: 0.1,
      シダーウッド: 0.25,
      パチュリ: 0.15,
      サンダルウッド: 0.1,
      ムスク: 0.1,
    },
  }),
  frag({
    id: "bleu-de-chanel",
    name: "Bleu de Chanel",
    nameJa: "ブルー ドゥ シャネル",
    brand: "CHANEL",
    category: "ウッディ・フレッシュ",
    gender: "men",
    vector: {
      レモン: 0.1,
      グレープフルーツ: 0.1,
      ベルガモット: 0.05,
      ジャスミン: 0.05,
      ラベンダー: 0.05,
      ブラックペッパー: 0.05,
      シダーウッド: 0.2,
      サンダルウッド: 0.15,
      パチュリ: 0.1,
      ムスク: 0.1,
      アンバー: 0.05,
    },
  }),
  frag({
    id: "sauvage",
    name: "Sauvage",
    nameJa: "ソヴァージュ",
    brand: "Dior",
    category: "ウッディ・フレッシュ",
    gender: "men",
    vector: {
      ベルガモット: 0.15,
      グレープフルーツ: 0.05,
      ラベンダー: 0.1,
      ブラックペッパー: 0.15,
      シダーウッド: 0.15,
      パチュリ: 0.1,
      アンバー: 0.15,
      ムスク: 0.1,
      サンダルウッド: 0.05,
    },
  }),

  // ─── ウッディ・ウォーム ───
  frag({
    id: "oud-wood",
    name: "Oud Wood",
    nameJa: "ウード ウッド",
    brand: "Tom Ford",
    category: "ウッディ・ウォーム",
    gender: "unisex",
    vector: {
      カーネーション: 0.05,
      ブラックペッパー: 0.05,
      サンダルウッド: 0.25,
      シダーウッド: 0.15,
      パチュリ: 0.15,
      アンバー: 0.15,
      レザー: 0.1,
      ムスク: 0.1,
    },
  }),
  frag({
    id: "man-in-black",
    name: "Man in Black",
    nameJa: "マン イン ブラック",
    brand: "Bvlgari",
    category: "ウッディ・ウォーム",
    gender: "men",
    vector: {
      ベルガモット: 0.05,
      チュベローズ: 0.05,
      カーネーション: 0.1,
      ブラックペッパー: 0.1,
      レザー: 0.2,
      アンバー: 0.2,
      サンダルウッド: 0.15,
      パチュリ: 0.1,
      ムスク: 0.05,
    },
  }),

  // ─── オリエンタル ───
  frag({
    id: "shalimar",
    name: "Shalimar",
    nameJa: "シャリマー",
    brand: "Guerlain",
    category: "オリエンタル",
    gender: "women",
    vector: {
      ベルガモット: 0.1,
      レモン: 0.05,
      ジャスミン: 0.1,
      スウィートローズ: 0.1,
      バニラ: 0.25,
      アンバー: 0.2,
      サンダルウッド: 0.1,
      ムスク: 0.1,
    },
  }),
  frag({
    id: "opium",
    name: "Opium",
    nameJa: "オピウム",
    brand: "Yves Saint Laurent",
    category: "オリエンタル",
    gender: "women",
    vector: {
      ベルガモット: 0.05,
      オレンジ: 0.05,
      ジャスミン: 0.1,
      カーネーション: 0.1,
      ダフネ: 0.05,
      アンバー: 0.2,
      バニラ: 0.15,
      サンダルウッド: 0.15,
      パチュリ: 0.1,
      ムスク: 0.05,
    },
  }),
  frag({
    id: "angel",
    name: "Angel",
    nameJa: "エンジェル",
    brand: "Mugler",
    category: "オリエンタル",
    gender: "women",
    vector: {
      ベルガモット: 0.05,
      カシス: 0.05,
      ジャスミン: 0.05,
      ダフネ: 0.05,
      バニラ: 0.25,
      パチュリ: 0.25,
      アンバー: 0.15,
      サンダルウッド: 0.1,
      ムスク: 0.05,
    },
  }),

  // ─── バランス型 ───
  frag({
    id: "leau-dissey",
    name: "L'Eau d'Issey",
    nameJa: "ロードゥ イッセイ",
    brand: "Issey Miyake",
    category: "バランス",
    gender: "women",
    vector: {
      レモン: 0.1,
      ベルガモット: 0.05,
      ミュゲ: 0.15,
      スウィートローズ: 0.1,
      ラベンダー: 0.1,
      シダーウッド: 0.15,
      ムスク: 0.2,
      サンダルウッド: 0.1,
      アンバー: 0.05,
    },
  }),
  frag({
    id: "le-male",
    name: "Le Male",
    nameJa: "ル マル",
    brand: "Jean Paul Gaultier",
    category: "バランス",
    gender: "men",
    vector: {
      ベルガモット: 0.1,
      オレンジ: 0.05,
      ラベンダー: 0.2,
      カーネーション: 0.05,
      バニラ: 0.2,
      アンバー: 0.15,
      サンダルウッド: 0.1,
      ムスク: 0.15,
    },
  }),
];
